### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mationai** [pouya-eghbali/bean#1]
What is .beef? Googling didn't help...

**Comment by pouya-eghbali** [comment]
Hello, it's a custom language designed for beef. It's a very simple, and limited language for describing language grammars (in bean format). Each line contains one rule, each rule must have 3 parts: left, right and name:

```
left right => name
```

left and right should be name (or names) of the rules | tokens to match, for example:

```
number|string add => addition_start
```

will expect a (number or string) on left side, and a add token on right side, if matched it will pack them in a token named addition_start.

Optionally each rule can have a meta attribute, this is used to manipulate the parse tree, for example:

```
number|string add => addition_start {type: left.type, lhs: left}
```

I made beef because I didn't want to manually make bean token | rule objects.

**Comment by mationai** [comment]
So running `node parser.js` produces the parse tree of `test.clio`. How do you verify it's correct?

**Comment by pouya-eghbali** [comment]
We don't have any tests for now, but soon I'll add.

**Comment by pouya-eghbali** [comment]
I've made a csv parser using bean, the grammar file is located here:

https://github.com/pouya-eghbali/ncsv/blob/master/ncsv.beef

you can use the vscode extension to highlight it.
